### ISSUE TITLE
Shared Calendars not accessible from remote program

### ISSUE THREAD

**Issue by matthiasbeyer** [agendav/agendav#106]
I tested with Thunderbird.

A shared calendar is not accessible for me by its URL. The log says:

```
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:--> <need-privileges>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:-->  <resource>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:-->   <href>/caldav.php/SOMEUSERNAME/</href>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:-->   <privilege>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:-->    <read/>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:-->   </privilege>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:-->  </resource>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:--> </need-privileges>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:--></error>
[Thu Sep 26 09:31:29 2013] [error] [client 141.28.95.55] davical: LOG: response:-->
```

When trying to sync a shared calendar with thunderbird. Am I missing some settings?

**Comment by C-Duv** [comment]
Thanks for sharing.
I have the same issue, let's hope this get fixed in Lightning client.
In the mean time I have added the _Read Current User's Access_ permission in _Privileges granted to All Users_ on the user whose the collection belongs to.

Maybe DAViCal could add a "permission compatibility" setting that make it automatically answer as if that permission was checked?

**Comment by adobo** [comment]
DAViCal could have that _compatibility mode_, but if no permissions were given to the principal URL by its owner, why should it give a possitive answer?

I hope the ticket gets some attention and someone agrees with us that the OPTIONS request makes no sense when Lightning does not have features like calendar autodiscovery. Given that Lightning expects single calendar URLs, it should just load the calendar :disappointed:
