### ISSUE TITLE
Update documentation (composer needed)

### ISSUE THREAD

**Issue by camlafit** [agendav/agendav#123]
Hi

Is it possible to add in documentation, this step : 
- cd web/
- php -r "readfile('https://getcomposer.org/installer');" | php
- php composer.phar install

As said in issue #99 , but documentation is always outdated :/

How can we help to update documentation ?

**Comment by petrk94** [comment]
Its 2019, and there is still no update in http://docs.agendav.org/en/2.2.0/admin/installation/
I have downloaded the latest release and there is no information where to make composer install
