### ISSUE TITLE
Doc  : minor issue but a little bit annoying

### ISSUE THREAD

**Issue by luffah** [agendav/agendav#207]
Hello i'm not english native, so when i read the doc. I don't really read, I apply commands.
On the installation procedure . On database populate, i made some time to understand i have to create the settings.php file.
http://docs.agendav.org/en/stable/admin/installation/#downloading-agendav-and-uncompressing

Maybe, it could be easier for noobs to indicate the sqlite procedure with "cp file.defaut.php file.php" and invite doc users to go to the advanced DB configuration.

**Comment by adobo** [comment]
@luffah I improved the installation guide to make easier following it step by step.

Thank you for your suggestions!

PS: please, please, please, do not blindly execute anything found on a installation guide :warning:
