### ISSUE TITLE
No synchro with baikal 

### ISSUE THREAD

**Issue by benjbubu** [agendav/agendav#211]
Hi everyone. 

I have a baikal server with agendav. I use baikal with my Android phone to sync all my events. Everything is connecting but since a few days, when i create an event on  agendav it doesnt sync on my phone. It doesnt work in the other way. It was already working and i dont know why it stop now. Could you help me ? Where do i need to look first ?

**Comment by adobo** [comment]
Does AgenDAV show those events when you reload the application or use the "Refresh" button?

If it does, then you should check your baikal logs to see if there are any issues with your phone synchronization. AgenDAV does not have an intermediate cache (yet), so events shown by the application are actually stored and served by the CalDAV server (baikal in your case).

**Comment by benjbubu** [comment]
OK your post help me a lot. If agendav only show whats in the baikal server sont the problem come from my phone. Indeed my phone stopped to autosync with baikal. I Just configure the account again and tadaaa. Sync is ok !
