### ISSUE TITLE
SSL self signed certificate problem

### ISSUE THREAD

**Issue by n1md4** [agendav/agendav#216]
Running 2.1 with caldav.certificate.verify set to false, but still receiving this error:

`[2017-06-27 11:32:33] agendav.CRITICAL: GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (uncaught exception) at /srv/domain.com/agendav/web/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 187 {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 60: SSL certificate problem: self signed certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /srv/domain.com/agendav/web/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187)"} []
`

Any help please?

**Comment by n1md4** [comment]
No one else has this problem with self-signed certificates?  Possible that the problem with the application's feature to override verification not working is entirely contained within my setup?

**Comment by adobo** [comment]
@n1md4 sorry, can't reproduce it here. I configured a really ugly certificate (self signed, no matching CN) on the CalDAV server, and set `caldav.certificate.verify` to false on `settings.php` I didn't have any issues connecting to it.

Setting `caldav.certificate.verify` back to true made AgenDAV not being able to connect to the server, as expected.

What is your running environment? Can you make sure the setting is actually set to `false` inside `settings.php`?

**Comment by adobo** [comment]
My fault, I should have clarified that AgenDAV 2.1.0 **does not** support `caldav.certificate.verify`. AgenDAV 2.2.0 does though.

Can you confirm AgenDAV 2.2.0 honors the setting?

**Comment by n1md4** [comment]
On 2017-08-22 11:05, Jorge López Pérez wrote:
> My fault, I should have clarified that AgenDAV 2.1.0 DOES NOT support
> caldav.certificate.verify. AgenDAV 2.2.0 does though.
> 
> Can you confirm AgenDAV 2.2.0 honors the setting?

Upgrading from 2.1 to 2.2 now works.

**Comment by adobo** [comment]
Glad to read it works as expected on 2.2.0!
