### ISSUE TITLE
language mix

### ISSUE THREAD

**Issue by huckley** [agendav/agendav#223]
I select German as Language. But I see a mix as German and English.
I use Version 2.2.0. 
For example in  ./web/lang/de_DE.php:
    'labels.october' => 'Oktober',

But I see: October.
![screenshot-2017-10-12 unser kalender](https://user-images.githubusercontent.com/21240087/31516244-35789df6-af98-11e7-83a9-ba51d246ee47.png)

**Comment by mmoll** [comment]
I can reproduce this on my prod install. I guess the fullcalender locales need to get added to the precompiled assets (or that path needs special handling) as the browser tries to reach out for a js file with the wrong URL.

**Comment by mmoll** [comment]
@huckley could you please test the patch in GH-224? After applying the patch delete the directories under `web/var/cache/twig/` in your agendav directory and reload in your browser.

**Comment by huckley** [comment]
Yes, this patch works.
Thanks.

**Comment by amino0** [comment]
I delete the cache _web/var/cache/twig_
 but there is nothing.
how should I go about it
