### ISSUE TITLE
Look and feel

### ISSUE THREAD

**Issue by mickael-kerjean** [agendav/agendav#246]
Hi there,

I'm evaluating agendav to connect to a Radicale server but as I wasn't a big fan of the general look and feel, I made a few changes and thought you might be curious to see what  it looks like now:

![screenshot_20180621_130706](https://user-images.githubusercontent.com/13233076/41695849-4a473d00-7554-11e8-8046-92423daee575.png)

It's still a WIP for now but I'll publish the changes when it's complete

**Comment by ScrumpyJack** [comment]
Did you end up publishing these changes? Was the intention to add to filestash?

**Comment by mickael-kerjean** [comment]
> Was the intention to add to filestash?

No it's for my personal use

> Did you end up publishing these changes?

I would have but I thought no one answering meant there's absolutly no interest. Now that I see 3 people reacting to the initial message, [here it is](https://github.com/mickael-kerjean/agendav-theme)
