### ISSUE TITLE
Remove reference of magic_quotes_runtime in the requirements

### ISSUE THREAD

**Issue by dilyanpalauzov** [agendav/agendav#251]
http://docs.agendav.org/en/2.2.0/admin/installation/#web-server-configuration says at least PHP 5.5 is required and `magic_quotes_runtime` must be turned off.  However since PHP 5.4 there is [no `magic_quotes_runtime`](http://php.net/manual/en/info.configuration.php#ini.magic-quotes-runtime).

**Comment by pixelbrackets** [comment]
fixed in `development` branch.
