### ISSUE TITLE
Placeholders in calendar URL with 2.x

### ISSUE THREAD

**Issue by lynix** [agendav/agendav#254]
I'd like to connect to a Radicale instance using AgenDAV 2.2.0. Therefore I need the calendar URL to contain the username, e.g. `https://caldav.example.org/lynix/calendar.ics`.

For old versions of AgenDAV (1.x) I find lots of `settings.php` examples like the following:
```php
$config['caldav_principal_url'] = 'https://caldav.example.org/%u/';
$config['caldav_calendar_url'] = 'https://caldav.example.org/%s/';
```
However for 2.x these placeholders seem to be not supported anymore. I tried the following but `%u` remained untouched in the HTTP request:
```php
$app['caldav.baseurl'] = 'https://caldav.example.org/%u/';
```

Is there a way to make calendar URLs contain the username for recent AgenDAV versions?

**Comment by H4usi** [comment]
+1
My CalDav Server also uses the Username in the URL. It would be very nice if this gets supported again.
