### ISSUE TITLE
PHP Warning:  count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by tanzhenchao** [agendav/agendav#256]
The following error message is received in the log，
[Wed Jan 30 16:31:14.965102 2019] [php7:warn] [pid 7440:tid 139706733651712] [client 10.168.0.8:8197] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/agendav/web/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 68, referer: http://agendav.cmdschool.org/

**Comment by JonTabor** [comment]
I receive this error when using PHP 7.3; however, using PHP 7.1, everything works properly.

**Comment by JodliDev** [comment]
This is a problem of guzzle (see https://github.com/guzzle/guzzle/issues/1973).

Just update guzzle in web/composer.json to at least 6.3 and run `npm install` and `npm run dist`

**Comment by pixelbrackets** [comment]
See #291, fixed in `development` branch, will be part of the next release.
