### ISSUE TITLE
[wish] allow 'multiweek' view

### ISSUE THREAD

**Issue by smu** [agendav/agendav#26]
I would like to see a multiweek view in agendav, similar to the one that can be found in lightning: four rows/weeks are shown with the current week in the top row.

thanks a lot for agendav!

cheers, 
 stefan

**Comment by nagimov** [comment]
for agendav 2.2.0 (fullcalendar 3.4.0) replacement of 1 month duration with 3 weeks duration in a month view: `sed -i 's/duration:{months:1}/duration:{weeks:3}/g' /var/www/agendav/web/public/dist/js/agendav.min.js`
