### ISSUE TITLE
All new entries shifted on one hour after change to sommer time

### ISSUE THREAD

**Issue by lucabert** [agendav/agendav#272]
After change to sommer time, all new entries I'll add or modify are shifted one hour in the future.
Agendav 2.2.0 is configured to the right timezone (for me Europe/Berlin).

Do someone have an explanation and (better!) a solution?

Thanks
Luca

**Comment by adri-M** [comment]
Same with Agendav 1.2.6, from winter to summer time 2021. Right timezone also (for me Europe/Paris).
Up-to-date debian server with PHP7
Working well since few years and first time i met this issue. Very strange!

**Comment by lucabert** [comment]
Forgotten: I updated my Server to Debian 10 about a month ago. Now Agendav works with PHP 7.3 (Timezone set to Europe/Berlin)
I'm pretty sure, in October, by changing to winter time, I didn't had any problem, and last year by changing to sommer time, too...

I see the hidden field "start" and "end" have the wrong value, since they should contains the time in UTC, but this is surely GMT (**with sommer time**).

Any idea?

**Comment by jorgelzpz** [comment]
:wave: I had to deal with this problem last week, and I found an explanation (and a fix) for it. AgenDAV ships with a library called [moment-timezone](https://momentjs.com/timezone/), which is used in the frontend. It offers several options when downloading it regarding the timezone data included along the code, such as _no data at all_, _10 years from now_ and _all data_.

When AgenDAV first included it I suspect I added the _10 years from now_ version; I probably thought in the following 10 years it would get updated by me or somebody else, and guess who never touched it again. Exactly. Nobody.

I suspect this happened in 2011. 10 years later the last daylight saving time change is completely out of range of the library coverage, which means dates past that change are simply wrong.

The solution is really easy: replace `assets/js/core/002-moment-timezone.min.js` with the last _with [full] data_ version from [moment-timezone website](https://momentjs.com/timezone/). Then run `npm run build:js` and force a reload of your browser cache.

Unfortunately my involvement on AgenDAV was halted some time ago. This means I'm probably not going to release a new version including the fix, but feel free to contribute a PR and I will happily merge it.

**Comment by adri-M** [comment]
Jorge, it's fantastic. Thank you so much for your help on this issue.
I use Agendav since the very beginning of the projet, sad news about the your future investments in Agendav (but not surpised). I will move to another frontend if there is no active contributors anymore (already in the pipe), but as you know there do not seem to be many alternatives with both davical compatibility and calendar sharing.

**Comment by lucabert** [comment]
Hi Jorge
I'm not sure, which file do you mean... In the page you suggest, I see:
moment-timezone-with-data-10-year-range.js
moment-timezone-with-data-1970-2030.js
moment-timezone-with-data.js
moment-timezone.js (no data)

Which is the "full" version?

Thanks
Luca

**Comment by lucabert** [comment]
OK, I got it too!
Jorge, you are my hero!!!
