### ISSUE TITLE
Delete one instance of a repeated event (occurences).

### ISSUE THREAD

**Issue by adri-M** [agendav/agendav#30]
Hi team.

When you add a repeated event, for exemple:
- Repetition: each week
- To 31/12/2012

After that, you have no possibility to delete only one event of this repeated event.

You can just delete all instances...

Is-there a solution to permit the deletion of only one occurence, as ical or lightning do?

In lightning you have the choice:
- Edit just this occurrence
- Edit all occurences

Regards,

**Comment by klickagent** [comment]
Oh, my mistake. Sorry for the duplication!
