### ISSUE TITLE
Cannot complete table creation. Thrown exception with Redis

### ISSUE THREAD

**Issue by unalignedcoder** [agendav/agendav#307]
When I run the command
`php agendavcli migrations:migrate`
I get this error:

`Fatal error: Uncaught RedisException: Connection refused in <server_path>/public_html/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php:137`

The line in the mentioned Setup.php is the following: 

`$redis->connect('127.0.0.1');`

I don't even need Redis, to be honest. Don't know why it's trying to connect to it upon install.

**Comment by pixelbrackets** [comment]
Take a look at this issue: https://github.com/agendav/agendav/issues/265#issuecomment-602077062

Your host probably has Redis available as PHP module, but you dont use it. This leads to a catch22 situation, because the framework used in this porject tries to use Redis by default afaik. A manual solution is described in the issue.

**Comment by unalignedcoder** [comment]
I don't fully understand the manual fix described in that thread. I cannot find that `Connector.php` file anywhere. Which file should I modify? Is it `/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php` ?

**Comment by unalignedcoder** [comment]
Hm. Yes, I modified `Setup.php` on line `70`, (replacing `$isDevMode` with `true`) and the migration started.

However, it fails later:
```
Migration 20140812133707 failed during Post-Checks. Error There is no active transaction
  [PDOException]
  There is no active transaction
```
Probably a minor error with Doctrine. The tables do seem to have been created. 

However, loading the website returns a completely blank page, as it did before migration.
