### ISSUE TITLE
Login via http_authorization

### ISSUE THREAD

**Issue by ghost** [agendav/agendav#38]
The ability to auto login to AgenDAV through a single sign-on to another service would be a great feature

**Comment by julienmalik** [comment]
We have this implemented in the Yunohost agendav package via this patch :
https://github.com/YunoHost-Apps/agendav_ynh/blob/master/patches/00-add-http-auth.patch

We would very much like to have this functionnality upstream too.

@adobo any interest in integrating this feature ? we're happy to rework our patch as needed for a smoother integration. comments welcome.

cc @jeromelebleu

**Comment by Offerel** [comment]
+1

**Comment by pixelbrackets** [comment]
See https://github.com/agendav/agendav/commit/bc104f7c34917f662ed48a4d10db0f76f9d5f0be
