### ISSUE TITLE
Modifying events results in "Element was modified while you were editing it. Please, refresh."

### ISSUE THREAD

**Issue by copiesofcopies** [agendav/agendav#55]
This happens nearly every time I modify an event. AgenDAV believes the event has been modified since I began modifying it, but it has not. This error comes from /web/application/controllers/event.php, line 414. I don't fully understand the code here, but it appears that the "etag" associated with the event in AgenDAV doesn't match the one stored by the CalDAV server (radicale).

@adobo can you tell me the purpose of this code and what I can do to track down the source of the error? Thanks!

**Comment by florihupf** [comment]
Hi @copiesofcopies. I am running into the same issue and also using Radicale (latest).  Did you ever figure it out?  Thank you!

**Comment by copiesofcopies** [comment]
@florihupf sorry, no, I never did.

**Comment by florihupf** [comment]
Hi @copiesofcopies. Thanks for the update! ;-) I do some digging...
