### ISSUE TITLE
Easy WebInstaller for NON-PRIVAT Webservers

### ISSUE THREAD

**Issue by Merowinger** [agendav/agendav#74]
Hey there,

I like your screenshots and try to set up agendav in my web environement running already roundcube and sabredav. I already tested massive tine2.0 and phpgroupware that were to huge for my simple wish (multiple calendars in web envireonment).

my issue:
Your filestructure web/public, web/System etc. makes the install hard when no alias are able to set. Copied all directories into root but I am not able to identify all necessary file redirects. Includes and Requiere_once went wrong.
Even when i copy and configure agendav as is pointing my browser to Domain/public/index.php i get an server error 500 because codeigniter is searching web/application/config/config.php that does not exist - correct search would be web/config/config.php

my hope:
Thus, I would apreciate an agendav version as easy to install as roundcube where files and structure are prohibited from running instead of necessity of alias.

Regards!
Berlinerfee

**Comment by derStephan** [comment]
Maybe it is best to setup a subdomain and point this directly to /web/public.
